#- pam_limits: domain=* limit_type=hard limit_item=nofile value=50000
#- pam_limits: domain=* limit_type=soft limit_item=nofile value=50000
#- pam_limits: domain=* limit_type=hard limit_item=nproc value=10000
#- pam_limits: domain=* limit_type=soft limit_item=nproc value=10000

- sysctl: name=vm.swappiness value=0 state=present
- sysctl: name=net.ipv4.ip_local_port_range value="10000 65000" state=present
#- sysctl: name=net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait=1 state=present

# Update all packages to the latest version
- apt: upgrade=yes

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

- name: Install Java 7
  apt: name=openjdk-7-jdk

- name: Install maven
  apt: name=maven

- apt: name=git state=present
- apt: name=build-essential state=present
- apt: name=python-dev
- name: System | Install system packages
  apt: name=python-pip

- pip: name=elasticsearch
- pip: name=twython
- pip: name=python-dateutil
- pip: name=facebook-sdk
- pip: name=facebook state=absent
- pip: name=pyopenssl
- pip: name=ndg-httpsclient
- pip: name=pyasn1
- pip: name=urllib3 version=1.10

